# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/qtcreator/block-panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 280)
        Form.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color:white;\n"
"    font-size:14px;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: gray;\n"
"}\n"
"\n"
"QTableWidget {\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    border: 0px; \n"
"    padding: 5px;\n"
"    color: black;\n"
"}\n"
"\n"
"QHeaderView {\n"
"  background: Grey;\n"
"  color:white;\n"
" \n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background: Grey;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QTableView::item:selected {\n"
"    background-color: rgb(223, 235, 244)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timelineWidget = QtWidgets.QWidget(Form)
        self.timelineWidget.setObjectName("timelineWidget")
        self.verticalLayout.addWidget(self.timelineWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(148)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.blockTextEdit = QtWidgets.QPlainTextEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockTextEdit.sizePolicy().hasHeightForWidth())
        self.blockTextEdit.setSizePolicy(sizePolicy)
        self.blockTextEdit.setStyleSheet(".QPlainTextEdit {\n"
"    font: 10pt \"PT Mono\";\n"
"}")
        self.blockTextEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.blockTextEdit.setLineWidth(0)
        self.blockTextEdit.setReadOnly(True)
        self.blockTextEdit.setObjectName("blockTextEdit")
        self.horizontalLayout.addWidget(self.blockTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Timeline"))
        self.tableWidget.setSortingEnabled(True)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Start"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "End"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Duration"))
