# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtcreator/catalogs.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_catalogWidget(object):
    def setupUi(self, catalogWidget):
        catalogWidget.setObjectName("catalogWidget")
        catalogWidget.resize(656, 421)
        catalogWidget.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color:white;\n"
"    font-size:14px;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: gray;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(catalogWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(catalogWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.refreshButton = QtWidgets.QPushButton(catalogWidget)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_4.addWidget(self.refreshButton)
        self.removeButton = QtWidgets.QPushButton(catalogWidget)
        self.removeButton.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"}")
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout_4.addWidget(self.removeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.current_catalogs = QtWidgets.QListWidget(catalogWidget)
        self.current_catalogs.setObjectName("current_catalogs")
        self.verticalLayout.addWidget(self.current_catalogs)
        self.label = QtWidgets.QLabel(catalogWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.reloadButton = QtWidgets.QPushButton(catalogWidget)
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout_3.addWidget(self.reloadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.session_catalogs = QtWidgets.QListWidget(catalogWidget)
        self.session_catalogs.setObjectName("session_catalogs")
        self.verticalLayout.addWidget(self.session_catalogs)
        self.label_3 = QtWidgets.QLabel(catalogWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.retranslateUi(catalogWidget)
        QtCore.QMetaObject.connectSlotsByName(catalogWidget)

    def retranslateUi(self, catalogWidget):
        _translate = QtCore.QCoreApplication.translate
        catalogWidget.setWindowTitle(_translate("catalogWidget", "Catalogs"))
        self.label_2.setText(_translate("catalogWidget", "Loaded Catalogs"))
        self.refreshButton.setText(_translate("catalogWidget", "Refresh Catalog"))
        self.removeButton.setText(_translate("catalogWidget", "Remove Selected"))
        self.label.setText(_translate("catalogWidget", "Session Catalogs"))
        self.reloadButton.setText(_translate("catalogWidget", "Reload Selected"))
        self.label_3.setText(_translate("catalogWidget", "Warning!\n"
"Manipulating manually catalog files can be dangerous and may cause malfunction in the application."))
