# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'console.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_consoleWidget(object):
    def setupUi(self, consoleWidget):
        consoleWidget.setObjectName("consoleWidget")
        consoleWidget.resize(515, 396)
        consoleWidget.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color:white;\n"
"    font-size:14px;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: gray;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(consoleWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(consoleWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.expressionEditor = QtWidgets.QPlainTextEdit(consoleWidget)
        self.expressionEditor.setObjectName("expressionEditor")
        self.verticalLayout.addWidget(self.expressionEditor)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.runButton = QtWidgets.QPushButton(consoleWidget)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_3.addWidget(self.runButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(consoleWidget)
        QtCore.QMetaObject.connectSlotsByName(consoleWidget)

    def retranslateUi(self, consoleWidget):
        _translate = QtCore.QCoreApplication.translate
        consoleWidget.setWindowTitle(_translate("consoleWidget", "Expression Console"))
        self.label.setText(_translate("consoleWidget", "Expressions"))
        self.runButton.setText(_translate("consoleWidget", "Run"))
