# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'landing.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_landingWidget(object):
    def setupUi(self, landingWidget):
        landingWidget.setObjectName("landingWidget")
        landingWidget.resize(373, 396)
        landingWidget.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color:white;\n"
"    font-size:14px;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: gray;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(landingWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(landingWidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/icons/ess_logo.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(landingWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(landingWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.selectButton = QtWidgets.QPushButton(landingWidget)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_3.addWidget(self.selectButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(landingWidget)
        QtCore.QMetaObject.connectSlotsByName(landingWidget)

    def retranslateUi(self, landingWidget):
        _translate = QtCore.QCoreApplication.translate
        landingWidget.setWindowTitle(_translate("landingWidget", "Basic Scene"))
        self.label_3.setText(_translate("landingWidget", "ESS Cosmographia Plugin"))
        self.comboBox.setItemText(0, _translate("landingWidget", "JUICE"))
        self.comboBox.setItemText(1, _translate("landingWidget", "TGO"))
        self.selectButton.setText(_translate("landingWidget", "Select Mission"))
from . import icons_rc
