# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtcreator/mk-loader.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mkLoaderWidget(object):
    def setupUi(self, mkLoaderWidget):
        mkLoaderWidget.setObjectName("mkLoaderWidget")
        mkLoaderWidget.resize(515, 396)
        mkLoaderWidget.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color:white;\n"
"    font-size:14px;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: gray;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(mkLoaderWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(mkLoaderWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mkInput = QtWidgets.QLineEdit(mkLoaderWidget)
        self.mkInput.setObjectName("mkInput")
        self.horizontalLayout.addWidget(self.mkInput)
        self.mkButton = QtWidgets.QPushButton(mkLoaderWidget)
        self.mkButton.setSizeIncrement(QtCore.QSize(3, 3))
        self.mkButton.setStyleSheet("QPushButton {\n"
"    background-color: gray;\n"
"}")
        self.mkButton.setObjectName("mkButton")
        self.horizontalLayout.addWidget(self.mkButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(mkLoaderWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.extraInput = QtWidgets.QLineEdit(mkLoaderWidget)
        self.extraInput.setObjectName("extraInput")
        self.horizontalLayout_4.addWidget(self.extraInput)
        self.extraBrowseButton = QtWidgets.QPushButton(mkLoaderWidget)
        self.extraBrowseButton.setStyleSheet("QPushButton {\n"
"    background-color: gray;\n"
"}")
        self.extraBrowseButton.setObjectName("extraBrowseButton")
        self.horizontalLayout_4.addWidget(self.extraBrowseButton)
        self.extraAddButton = QtWidgets.QPushButton(mkLoaderWidget)
        self.extraAddButton.setStyleSheet("QPushButton {\n"
"    background-color: gray;\n"
"}")
        self.extraAddButton.setObjectName("extraAddButton")
        self.horizontalLayout_4.addWidget(self.extraAddButton)
        self.extraResetButton = QtWidgets.QPushButton(mkLoaderWidget)
        self.extraResetButton.setStyleSheet("QPushButton {\n"
"    background-color: orange;\n"
"}")
        self.extraResetButton.setObjectName("extraResetButton")
        self.horizontalLayout_4.addWidget(self.extraResetButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.extraList = QtWidgets.QListWidget(mkLoaderWidget)
        self.extraList.setObjectName("extraList")
        self.verticalLayout.addWidget(self.extraList)
        self.label_3 = QtWidgets.QLabel(mkLoaderWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(mkLoaderWidget)
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2031, 8, 16), QtCore.QTime(20, 0, 0)))
        self.dateTimeEdit.setDate(QtCore.QDate(2031, 8, 16))
        self.dateTimeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2050, 12, 31), QtCore.QTime(19, 59, 57)))
        self.dateTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2010, 1, 1), QtCore.QTime(17, 0, 0)))
        self.dateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout.addWidget(self.dateTimeEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.visualizeButton = QtWidgets.QPushButton(mkLoaderWidget)
        self.visualizeButton.setObjectName("visualizeButton")
        self.horizontalLayout_3.addWidget(self.visualizeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(mkLoaderWidget)
        QtCore.QMetaObject.connectSlotsByName(mkLoaderWidget)
        mkLoaderWidget.setTabOrder(self.mkInput, self.mkButton)

    def retranslateUi(self, mkLoaderWidget):
        _translate = QtCore.QCoreApplication.translate
        mkLoaderWidget.setWindowTitle(_translate("mkLoaderWidget", "Basic Scene"))
        self.label.setText(_translate("mkLoaderWidget", "Metakernel File"))
        self.mkButton.setText(_translate("mkLoaderWidget", " Browse "))
        self.label_2.setText(_translate("mkLoaderWidget", "Additional kernels"))
        self.extraBrowseButton.setText(_translate("mkLoaderWidget", "Browse"))
        self.extraAddButton.setText(_translate("mkLoaderWidget", "Add"))
        self.extraResetButton.setText(_translate("mkLoaderWidget", "Clean all"))
        self.label_3.setText(_translate("mkLoaderWidget", "Date"))
        self.dateTimeEdit.setDisplayFormat(_translate("mkLoaderWidget", "yyyy-MM-ddTHH:mm:ss"))
        self.visualizeButton.setText(_translate("mkLoaderWidget", "Visualize"))
