# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtcreator/moons-panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(384, 369)
        Form.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color:white;\n"
"    font-size:14px;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: gray;\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Jupiter Structures"))
        self.label.setText(_translate("Form", "Jupiter Moons"))
