# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtcreator/navigator-panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(382, 89)
        Form.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color:white;\n"
"    font-size:14px;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: gray;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sensorViewButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensorViewButton.sizePolicy().hasHeightForWidth())
        self.sensorViewButton.setSizePolicy(sizePolicy)
        self.sensorViewButton.setObjectName("sensorViewButton")
        self.horizontalLayout.addWidget(self.sensorViewButton)
        self.sensorBox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensorBox.sizePolicy().hasHeightForWidth())
        self.sensorBox.setSizePolicy(sizePolicy)
        self.sensorBox.setObjectName("sensorBox")
        self.horizontalLayout.addWidget(self.sensorBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scViewButton = QtWidgets.QPushButton(Form)
        self.scViewButton.setObjectName("scViewButton")
        self.verticalLayout.addWidget(self.scViewButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frustrumCheckbox = QtWidgets.QCheckBox(Form)
        self.frustrumCheckbox.setObjectName("frustrumCheckbox")
        self.horizontalLayout_2.addWidget(self.frustrumCheckbox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Navigation"))
        self.sensorViewButton.setText(_translate("Form", "Sensor View"))
        self.scViewButton.setText(_translate("Form", "Spacecraft"))
        self.frustrumCheckbox.setText(_translate("Form", "Show Frustrum"))
