# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'observations-panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_observationsPanel(object):
    def setupUi(self, observationsPanel):
        observationsPanel.setObjectName("observationsPanel")
        observationsPanel.resize(796, 320)
        observationsPanel.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color:white;\n"
"    font-size:14px;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    padding-right: 5px;\n"
"    padding-left: 5px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #367c39;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    color: gray;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(observationsPanel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(observationsPanel)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.importLineEdit = QtWidgets.QLineEdit(observationsPanel)
        self.importLineEdit.setObjectName("importLineEdit")
        self.horizontalLayout_3.addWidget(self.importLineEdit)
        self.browseButton = QtWidgets.QPushButton(observationsPanel)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout_3.addWidget(self.browseButton)
        self.importButton = QtWidgets.QPushButton(observationsPanel)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_3.addWidget(self.importButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sensorComboBox = QtWidgets.QComboBox(observationsPanel)
        self.sensorComboBox.setObjectName("sensorComboBox")
        self.horizontalLayout.addWidget(self.sensorComboBox)
        self.targetComboBox = QtWidgets.QComboBox(observationsPanel)
        self.targetComboBox.setObjectName("targetComboBox")
        self.horizontalLayout.addWidget(self.targetComboBox)
        self.startDateTimeEdit = QtWidgets.QDateTimeEdit(observationsPanel)
        self.startDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.startDateTimeEdit.setObjectName("startDateTimeEdit")
        self.horizontalLayout.addWidget(self.startDateTimeEdit)
        self.endDateTimeEdit = QtWidgets.QDateTimeEdit(observationsPanel)
        self.endDateTimeEdit.setTimeSpec(QtCore.Qt.UTC)
        self.endDateTimeEdit.setObjectName("endDateTimeEdit")
        self.horizontalLayout.addWidget(self.endDateTimeEdit)
        self.newButton = QtWidgets.QPushButton(observationsPanel)
        self.newButton.setObjectName("newButton")
        self.horizontalLayout.addWidget(self.newButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(observationsPanel)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.addButton = QtWidgets.QPushButton(observationsPanel)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_4.addWidget(self.addButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(observationsPanel)
        QtCore.QMetaObject.connectSlotsByName(observationsPanel)

    def retranslateUi(self, observationsPanel):
        _translate = QtCore.QCoreApplication.translate
        observationsPanel.setWindowTitle(_translate("observationsPanel", "Observations"))
        self.label.setText(_translate("observationsPanel", "CSV Import"))
        self.browseButton.setText(_translate("observationsPanel", "Browse"))
        self.importButton.setText(_translate("observationsPanel", "Import CSV"))
        self.startDateTimeEdit.setDisplayFormat(_translate("observationsPanel", "yyyy-MM-ddTHH:mm:ss"))
        self.endDateTimeEdit.setDisplayFormat(_translate("observationsPanel", "yyyy-MM-ddTHH:mm:ss"))
        self.newButton.setText(_translate("observationsPanel", "New"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("observationsPanel", "Sensor"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("observationsPanel", "Target"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("observationsPanel", "Start"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("observationsPanel", "End"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("observationsPanel", "-"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("observationsPanel", "-"))
        self.addButton.setText(_translate("observationsPanel", "Add Observations"))
