# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ptr-editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ptrEditorWidget(object):
    def setupUi(self, ptrEditorWidget):
        ptrEditorWidget.setObjectName("ptrEditorWidget")
        ptrEditorWidget.resize(538, 376)
        ptrEditorWidget.setStyleSheet(" QPushButton {\n"
"                background-color: #4CAF50;\n"
"                color:white;\n"
"                font-size:18px;\n"
"                border:none;\n"
"                border-radius:10px;\n"
"            }\n"
"            \n"
"            QPushButton:hover {\n"
"                background-color: #45a049;\n"
"            }\n"
"            \n"
"            QPushButton:pressed {\n"
"                background-color: #367c39;\n"
"\n"
"            }")
        self.visualizeButton = QtWidgets.QPushButton(ptrEditorWidget)
        self.visualizeButton.setGeometry(QtCore.QRect(220, 330, 100, 32))
        self.visualizeButton.setObjectName("visualizeButton")
        self.ptrEditor = QtWidgets.QTextEdit(ptrEditorWidget)
        self.ptrEditor.setGeometry(QtCore.QRect(3, 3, 531, 311))
        self.ptrEditor.setObjectName("ptrEditor")

        self.retranslateUi(ptrEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(ptrEditorWidget)

    def retranslateUi(self, ptrEditorWidget):
        _translate = QtCore.QCoreApplication.translate
        ptrEditorWidget.setWindowTitle(_translate("ptrEditorWidget", "Form"))
        self.visualizeButton.setText(_translate("ptrEditorWidget", "Visualize"))
