# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ptr-editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ptrEditorWidget(object):
    def setupUi(self, ptrEditorWidget):
        ptrEditorWidget.setObjectName("ptrEditorWidget")
        ptrEditorWidget.resize(515, 396)
        ptrEditorWidget.setStyleSheet(" QPushButton {\n"
"                background-color: #4CAF50;\n"
"                color:white;\n"
"                font-size:18px;\n"
"                border:none;\n"
"                border-radius:10px;\n"
"            }\n"
"            \n"
"            QPushButton:hover {\n"
"                background-color: #45a049;\n"
"            }\n"
"            \n"
"            QPushButton:pressed {\n"
"                background-color: #367c39;\n"
"\n"
"            }")
        self.gridLayout = QtWidgets.QGridLayout(ptrEditorWidget)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.mkButton = QtWidgets.QPushButton(ptrEditorWidget)
        self.mkButton.setObjectName("mkButton")
        self.gridLayout.addWidget(self.mkButton, 2, 0, 1, 1)
        self.ptrEditor = QtWidgets.QTextEdit(ptrEditorWidget)
        self.ptrEditor.setObjectName("ptrEditor")
        self.gridLayout.addWidget(self.ptrEditor, 3, 0, 1, 1)
        self.mkInput = QtWidgets.QLineEdit(ptrEditorWidget)
        self.mkInput.setObjectName("mkInput")
        self.gridLayout.addWidget(self.mkInput, 1, 0, 1, 1)
        self.visualizeButton = QtWidgets.QPushButton(ptrEditorWidget)
        self.visualizeButton.setObjectName("visualizeButton")
        self.gridLayout.addWidget(self.visualizeButton, 4, 0, 1, 1)

        self.retranslateUi(ptrEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(ptrEditorWidget)

    def retranslateUi(self, ptrEditorWidget):
        _translate = QtCore.QCoreApplication.translate
        ptrEditorWidget.setWindowTitle(_translate("ptrEditorWidget", "PTR Editor"))
        self.mkButton.setText(_translate("ptrEditorWidget", "Browse Metakernel"))
        self.visualizeButton.setText(_translate("ptrEditorWidget", "Visualize"))
