# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtcreator/time-panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(517, 52)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(12, 3, 12, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.direction = QtWidgets.QToolButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/arrow_rotate_anticlockwise.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.direction.setIcon(icon)
        self.direction.setObjectName("direction")
        self.horizontalLayout.addWidget(self.direction)
        self.rewind = QtWidgets.QToolButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/control_rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rewind.setIcon(icon1)
        self.rewind.setObjectName("rewind")
        self.horizontalLayout.addWidget(self.rewind)
        self.forward = QtWidgets.QToolButton(Form)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/control_fastforward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forward.setIcon(icon2)
        self.forward.setObjectName("forward")
        self.horizontalLayout.addWidget(self.forward)
        self.play = QtWidgets.QToolButton(Form)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/control_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon3)
        self.play.setObjectName("play")
        self.horizontalLayout.addWidget(self.play)
        self.pause = QtWidgets.QToolButton(Form)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons/control_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon4)
        self.pause.setObjectName("pause")
        self.horizontalLayout.addWidget(self.pause)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.timeDisplay = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        self.timeDisplay.setFont(font)
        self.timeDisplay.setObjectName("timeDisplay")
        self.horizontalLayout.addWidget(self.timeDisplay)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.direction.setToolTip(_translate("Form", "Reverse"))
        self.direction.setText(_translate("Form", "..."))
        self.rewind.setToolTip(_translate("Form", "Time slower"))
        self.rewind.setText(_translate("Form", "..."))
        self.forward.setToolTip(_translate("Form", "Time faster"))
        self.forward.setText(_translate("Form", "..."))
        self.play.setToolTip(_translate("Form", "Play/Pause"))
        self.play.setText(_translate("Form", "..."))
        self.pause.setText(_translate("Form", "..."))
        self.timeDisplay.setToolTip(_translate("Form", "Current time"))
        self.timeDisplay.setText(_translate("Form", "time"))
from . import icons_rc
